Repository OpInCo-Community/HacktoberWeek, pull requests merged in 2022-10, with the labels that each got.

#6 Added design contribution folders and structure
  .DS_Store
  Design-Contributions/.DS_Store
  Design-Contributions/README.md
  Design-Contributions/Youtube/.DS_Store
Labels: hacktoberfest-accepted

#5 Note Keeping App added
  Android-Contributions/Note-Keeping-App/.gitignore
  Android-Contributions/Note-Keeping-App/.idea/.gitignore
  Android-Contributions/Note-Keeping-App/.idea/.name
  Android-Contributions/Note-Keeping-App/.idea/compiler.xml
  Android-Contributions/Note-Keeping-App/.idea/gradle.xml
  Android-Contributions/Note-Keeping-App/.idea/misc.xml
  Android-Contributions/Note-Keeping-App/.idea/vcs.xml
  Android-Contributions/Note-Keeping-App/app/.gitignore
  Android-Contributions/Note-Keeping-App/app/build.gradle
  Android-Contributions/Note-Keeping-App/app/proguard-rules.pro
  Android-Contributions/Note-Keeping-App/app/src/androidTest/java/com/anurag/notekeepingapp/ExampleInstrumentedTest.kt
  Android-Contributions/Note-Keeping-App/app/src/main/AndroidManifest.xml
  Android-Contributions/Note-Keeping-App/app/src/main/java/com/anurag/notekeepingapp/MainActivity.kt
  Android-Contributions/Note-Keeping-App/app/src/main/java/com/anurag/notekeepingapp/NoteApplication.kt
  Android-Contributions/Note-Keeping-App/app/src/main/java/com/anurag/notekeepingapp/NoteDao.kt
  Android-Contributions/Note-Keeping-App/app/src/main/java/com/anurag/notekeepingapp/NoteDataBase.kt
  Android-Contributions/Note-Keeping-App/app/src/main/java/com/anurag/notekeepingapp/NoteEntity.kt
  Android-Contributions/Note-Keeping-App/app/src/main/java/com/anurag/notekeepingapp/NoteRepository.kt
  Android-Contributions/Note-Keeping-App/app/src/main/java/com/anurag/notekeepingapp/NotesViewModel.kt
  Android-Contributions/Note-Keeping-App/app/src/main/java/com/anurag/notekeepingapp/NotesViewModelFactory.kt
  Android-Contributions/Note-Keeping-App/app/src/main/java/com/anurag/notekeepingapp/RecyclerViewAdapter.kt
  Android-Contributions/Note-Keeping-App/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/drawable/ic_baseline_add_circle_24.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/drawable/ic_baseline_delete_forever_24.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/drawable/ic_launcher_background.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/layout/activity_main.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/layout/note_item.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Android-Contributions/Note-Keeping-App/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Android-Contributions/Note-Keeping-App/app/src/main/res/values-night/themes.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/values/colors.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/values/strings.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/values/themes.xml
  Android-Contributions/Note-Keeping-App/app/src/test/java/com/anurag/notekeepingapp/ExampleUnitTest.kt
  Android-Contributions/Note-Keeping-App/build.gradle
  Android-Contributions/Note-Keeping-App/gradle.properties
  Android-Contributions/Note-Keeping-App/gradle/wrapper/gradle-wrapper.jar
  Android-Contributions/Note-Keeping-App/gradle/wrapper/gradle-wrapper.properties
  Android-Contributions/Note-Keeping-App/gradlew
  Android-Contributions/Note-Keeping-App/gradlew.bat
  Android-Contributions/Note-Keeping-App/settings.gradle
Labels: hacktoberfest, hacktoberfest-accepted

#13 readme.md and contibution.md added
  Android-Contributions/CONTRIBUTING.md
  Android-Contributions/README.md
Labels: documentation, hacktoberfest-accepted, android

#21 Adding app
  Android-Contributions/MemeShare/.gitignore
  Android-Contributions/MemeShare/.idea/.gitignore
  Android-Contributions/MemeShare/.idea/compiler.xml
  Android-Contributions/MemeShare/.idea/gradle.xml
  Android-Contributions/MemeShare/.idea/misc.xml
  Android-Contributions/MemeShare/app/.gitignore
  Android-Contributions/MemeShare/app/build.gradle
  Android-Contributions/MemeShare/app/proguard-rules.pro
  Android-Contributions/MemeShare/app/src/androidTest/java/com/example/memeshare/ExampleInstrumentedTest.kt
  Android-Contributions/MemeShare/app/src/main/AndroidManifest.xml
  Android-Contributions/MemeShare/app/src/main/java/com/example/memeshare/MainActivity.kt
  Android-Contributions/MemeShare/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Android-Contributions/MemeShare/app/src/main/res/drawable/circular_button.xml
  Android-Contributions/MemeShare/app/src/main/res/drawable/ic_launcher_background.xml
  Android-Contributions/MemeShare/app/src/main/res/drawable/icons8_trollface_48.png
  Android-Contributions/MemeShare/app/src/main/res/drawable/icons8_trollface_96.png
  Android-Contributions/MemeShare/app/src/main/res/drawable/progress_icon.xml
  Android-Contributions/MemeShare/app/src/main/res/layout/activity_main.xml
  Android-Contributions/MemeShare/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android-Contributions/MemeShare/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android-Contributions/MemeShare/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Android-Contributions/MemeShare/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Android-Contributions/MemeShare/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Android-Contributions/MemeShare/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Android-Contributions/MemeShare/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Android-Contributions/MemeShare/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Android-Contributions/MemeShare/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Android-Contributions/MemeShare/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Android-Contributions/MemeShare/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Android-Contributions/MemeShare/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Android-Contributions/MemeShare/app/src/main/res/values-night/themes.xml
  Android-Contributions/MemeShare/app/src/main/res/values/colors.xml
  Android-Contributions/MemeShare/app/src/main/res/values/strings.xml
  Android-Contributions/MemeShare/app/src/main/res/values/themes.xml
  Android-Contributions/MemeShare/app/src/main/res/xml/backup_rules.xml
  Android-Contributions/MemeShare/app/src/main/res/xml/data_extraction_rules.xml
  Android-Contributions/MemeShare/app/src/test/java/com/example/memeshare/ExampleUnitTest.kt
  Android-Contributions/MemeShare/build.gradle
  Android-Contributions/MemeShare/gradle.properties
  Android-Contributions/MemeShare/gradle/wrapper/gradle-wrapper.jar
  Android-Contributions/MemeShare/gradle/wrapper/gradle-wrapper.properties
  Android-Contributions/MemeShare/gradlew
  Android-Contributions/MemeShare/gradlew.bat
  Android-Contributions/MemeShare/settings.gradle
Labels: hacktoberfest-accepted, android

#36 Button shape changed to circle and color changed to blue
  Android-Contributions/Note-Keeping-App/app/src/main/java/com/anurag/notekeepingapp/MainActivity.kt
Labels: under-review

#55 create Splash Screen support for Android 12
  Android-Contributions/Note-Keeping-App/app/build.gradle
  Android-Contributions/Note-Keeping-App/app/src/main/AndroidManifest.xml
  Android-Contributions/Note-Keeping-App/app/src/main/java/com/anurag/notekeepingapp/MainActivity.kt
  Android-Contributions/Note-Keeping-App/app/src/main/res/values/splash_theme.xml
Labels: hacktoberfest-accepted

#57 updated ui
  Android-Contributions/Note-Keeping-App/.idea/misc.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/drawable/ic_add.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/drawable/ic_edit.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/layout/activity_main.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/layout/note_item.xml
  Android-Contributions/Note-Keeping-App/app/src/main/res/values/colors.xml
Labels: hacktoberfest-accepted

#58 Added Custom splash screen with lottie animation
  Android-Contributions/MemeShare/app/build.gradle
  Android-Contributions/MemeShare/app/src/main/AndroidManifest.xml
Labels: under-review

#62 Added readme for Note Keeping App
  Android-Contributions/Note-Keeping-App/README.md
Labels: hacktoberfest-accepted

#69 Created Readme
  Android-Contributions/QR_Code_Reader/Readme.md
Labels: hacktoberfest-accepted

#70 Resume Screening Model
  ML-Contributions/Resume_Screening_prajwal-144/Dataset/README.md
  ML-Contributions/Resume_Screening_prajwal-144/Images/Kvalue_error.png
  ML-Contributions/Resume_Screening_prajwal-144/Images/accuracy_comparison.png
  ML-Contributions/Resume_Screening_prajwal-144/Images/acuracy_comp(two).png
  ML-Contributions/Resume_Screening_prajwal-144/Images/category_count.png
  ML-Contributions/Resume_Screening_prajwal-144/Images/category_distribution.png
  ML-Contributions/Resume_Screening_prajwal-144/Images/confusion_matrix_ADB.png
  ML-Contributions/Resume_Screening_prajwal-144/Images/confusion_matrix_GB.png
  ML-Contributions/Resume_Screening_prajwal-144/Images/confusion_matrix_KNN.png
  ML-Contributions/Resume_Screening_prajwal-144/Images/confusion_matrix_MNB.png
  ML-Contributions/Resume_Screening_prajwal-144/Images/confusion_matrix_SGD.png
  ML-Contributions/Resume_Screening_prajwal-144/Images/confusion_matrix_descision_tree.png
  ML-Contributions/Resume_Screening_prajwal-144/Images/wordcloud.png
  ML-Contributions/Resume_Screening_prajwal-144/Model/README.md
  ML-Contributions/Resume_Screening_prajwal-144/Model/resume-classification_1.ipynb
  ML-Contributions/Resume_Screening_prajwal-144/requirements.txt
Labels: hacktoberfest-accepted

#72 Added Face Recognition App
  ML-Contributions/Face-recognition-app/FaceRecogBlock.png
  ML-Contributions/Face-recognition-app/FacialRecognition/01_face_dataset.py
  ML-Contributions/Face-recognition-app/FacialRecognition/02_face_training.py
  ML-Contributions/Face-recognition-app/FacialRecognition/03_face_recognition.py
  ML-Contributions/Face-recognition-app/FacialRecognition/haarcascade_frontalface_default.xml
  ML-Contributions/Face-recognition-app/README.md
Labels: hacktoberfest-accepted, ml

#32 [FIXED-30] Added "Change the View" Button
  Android-Contributions/Compose Camp/.gradle/7.3.3/checksums/checksums.lock
  Android-Contributions/Compose Camp/.gradle/7.3.3/dependencies-accessors/dependencies-accessors.lock
  Android-Contributions/Compose Camp/.gradle/7.3.3/dependencies-accessors/gc.properties
  Android-Contributions/Compose Camp/.gradle/7.3.3/executionHistory/executionHistory.bin
  Android-Contributions/Compose Camp/.gradle/7.3.3/executionHistory/executionHistory.lock
  Android-Contributions/Compose Camp/.gradle/7.3.3/fileChanges/last-build.bin
  Android-Contributions/Compose Camp/.gradle/7.3.3/fileHashes/fileHashes.bin
  Android-Contributions/Compose Camp/.gradle/7.3.3/fileHashes/fileHashes.lock
  Android-Contributions/Compose Camp/.gradle/7.3.3/fileHashes/resourceHashesCache.bin
  Android-Contributions/Compose Camp/.gradle/7.3.3/gc.properties
  Android-Contributions/Compose Camp/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Android-Contributions/Compose Camp/.gradle/buildOutputCleanup/cache.properties
  Android-Contributions/Compose Camp/.gradle/buildOutputCleanup/outputFiles.bin
  Android-Contributions/Compose Camp/.gradle/file-system.probe
  Android-Contributions/Compose Camp/.gradle/vcs-1/gc.properties
  Android-Contributions/Compose Camp/.idea/.name
  Android-Contributions/Compose Camp/.idea/compiler.xml
  Android-Contributions/Compose Camp/.idea/deploymentTargetDropDown.xml
  Android-Contributions/Compose Camp/.idea/gradle.xml
  Android-Contributions/Compose Camp/.idea/inspectionProfiles/Project_Default.xml
  Android-Contributions/Compose Camp/.idea/misc.xml
  Android-Contributions/Compose Camp/.idea/vcs.xml
  Android-Contributions/Compose Camp/.idea/workspace.xml
  Android-Contributions/Compose Camp/README.md
  Android-Contributions/Compose Camp/app/src/main/java/com/nikeight/compose_playground/ui/MainActivity.kt
  Android-Contributions/Compose Camp/app/src/main/java/com/nikeight/compose_playground/ui/gallery_app/screens/GalleryLandingScreen.kt
  Android-Contributions/Compose Camp/app/src/main/java/com/nikeight/compose_playground/ui/gallery_app/screens/GridGalleryScreen.kt
Labels: hacktoberfest-accepted

#61 New
  ML-Contributions/models/PI-ml.ipynb
  Technical-Documentaion/Day Blog/PiyushJoshi.md
Labels: hacktoberfest-accepted, ml
